OBJ_TANK = 1
OBJ_FASTTANK = 2
OBJ_PLAYERMISSILE = 3
OBJ_ENEMYMISSILE = 4
OBJ_GUIDEDMISSILE = 5
OBJ_SAUCER = 6

OBJ_PYRAMID = 7
OBJ_WIDEPYRAMID = 8
OBJ_TALLBOX = 9
OBJ_SHORTBOX = 10

OBJ_PROJECTILE_IMPACT = 11
OBJ_CHUNK = 12
OBJ_SPATTER = 13
OBJ_LOGO = 14
OBJ_DODO = 15


EVENT_HIT  =1
EVENT_PLAYER_MISSILE=2
EVENT_EXPLOSION=3
EVENT_PROJECTILE_IMPACT=4
EVENT_ENEMY_MISSILE = 5
EVENT_GUIDED_M_SPATTER = 6
EVENT_HORIZON_SHAKE = 7
EVENT_LAUNCH_GM = 8
EVENT_LAUNCH_SAUCER = 9
EVENT_SOUND_STOP = 10
EVENT_SOUND_VOLUME = 11
EVENT_SOUND_CRASH = 12


TANK_TIMEOUT = 30
SAUCER_INTERVAL = 90